disabled_rules:
  - trailing_comma

identifier_name:
  min_length:
    warning: 2
    error: 2
  excluded:
    - xs
    - sm
    - md
    - lg
    - xl
    - xxl
    - r
    - g
    - b

line_length:
  warning: 220
  error: 240

file_length:
  warning: 1400
  error: 1600

function_body_length:
  warning: 60
  error: 100
