disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - function_parameter_count
opt_in_rules:
  - closure_end_indentation
  - closure_body_length
  - empty_count
  - explicit_init
  - implicit_return
  - redundant_nil_coalescing
  - sorted_imports
included:
  - Sherpa
excluded:
  - SherpaUITests
  - SherpaTests
analyzer_rules:
  - unused_import
reporter: "xcode"
line_length:
  warning: 140
  error: 200
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 800
  error: 1200
identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
    - dx
    - dy
custom_rules:
  no_unmanaged_task:
    included: ".*\\.swift"
    name: "Prefer structured Task"
    regex: "_Concurrency\\.Task"
    message: "Use Task { } or .task(id:) unless you need detached semantics."
