name: iOS CI

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Optional note for manual run'
        required: false

jobs:
  build-test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 26.0.1 (iOS 18 SDK)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0.1'

      - name: Show Xcode & SDK
        run: |
          xcodebuild -version
          xcodebuild -showsdks

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      - name: Install Tooling
        run: |
          brew install swiftlint swiftformat peripheryapp/periphery/periphery || true

      - name: Lint
        run: ./Scripts/lint.sh

      - name: Format Check
        run: ./Scripts/format.sh --lint

      - name: Build & Test (Simulator)
        run: |
          xcodebuild \
            -project Sherpa.xcodeproj \
            -scheme Sherpa \
            -testPlan Config/Sherpa.xctestplan \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -enableCodeCoverage YES \
            -quiet test

      - name: Periphery (dead code)
        if: ${{ always() }}
        run: |
          ./Scripts/periphery.sh || true
